name: Github pages

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Yarn build
        run: yarn build:all
      - name: Release pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: out
          commit_message: Update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
